### ISSUE TITLE
parser.destructuringAssignmentPropertiesFor is not a function

### ISSUE THREAD

**Issue by BenjaminLesne** [BuilderIO/hydration-overlay#21]
This is related to #16 

I have upgraded to version 0.0.6 as suggested [here](https://github.com/BuilderIO/hydration-overlay/issues/16#issuecomment-1865731507)

I tried with the withHydrationOverlay and withHydrationOverlayWebpack, both lead to the same error. (see below)

When I start the dev server  and go to a page with an hydration error,  I get this in my terminal :

```bash
[benjamin@archlinux jegwell-t3]$ pnpm dev

> jegwell-t3@0.1.0 dev /home/benjamin/code/jegwell-t3
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- info Loaded env from /home/benjamin/code/jegwell-t3/.env
- error ./node_modules/.pnpm/@builder.io+react-hydration-overlay@0.0.6_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@builder.io/react-hydration-overlay/dist/hydration-overlay-initializer.js
Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
- wait compiling...
- wait compiling / (client and server)...
- error ./node_modules/.pnpm/@builder.io+react-hydration-overlay@0.0.6_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@builder.io/react-hydration-overlay/dist/hydration-overlay-initializer.js
Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
- wait compiling /_error (client and server)...
- error ./node_modules/.pnpm/@builder.io+react-hydration-overlay@0.0.6_react-dom@18.2.0_react@18.2.0_webpack@5.89.0/node_modules/@builder.io/react-hydration-overlay/dist/hydration-overlay-initializer.js
Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
- error Error: Cannot find module '/home/benjamin/code/jegwell-t3/.next/fallback-build-manifest.json'
Require stack:
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/render-server.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:180:36
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at loadDefaultErrorComponentsImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:40:24)
    at DevServer.getFallbackErrorComponents (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:1314:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.renderErrorToResponseImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1565:40)
    at async DevServer.renderToResponseImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1402:30)
    at async DevServer.pipeImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:627:25)
    at async Object.fn (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:1136:21)
    at async Router.execute (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:315:32)
    at async DevServer.runImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:601:29)
    at async DevServer.run (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:922:20)
    at async DevServer.handleRequestImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:533:20) {
  digest: undefined
}
Error: Cannot find module '/home/benjamin/code/jegwell-t3/.next/fallback-build-manifest.json'
Require stack:
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/render-server.js
- /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1072:15)
    at /home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/require-hook.js:180:36
    at Module._load (node:internal/modules/cjs/loader:925:27)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at require (node:internal/modules/helpers:121:18)
    at loadDefaultErrorComponentsImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js:40:24)
    at DevServer.getFallbackErrorComponents (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:1314:73)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.renderErrorToResponseImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1565:40)
    at async pipe.req.req (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:1439:30)
    at async DevServer.pipeImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:627:25)
    at async DevServer.run (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js:930:28)
    at async DevServer.handleRequestImpl (/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:533:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/load-components.js',
    '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js',
    '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/dev/next-dev-server.js',
    '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next.js',
    '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/render-server.js',
    '/home/benjamin/code/jegwell-t3/node_modules/.pnpm/next@13.4.1_@babel+core@7.21.8_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}
```

**Comment by BenjaminLesne** [comment]
Based on [this](https://stackoverflow.com/questions/76000975/nx-angular-project-build-failed-after-upgrading-to-webpack-5-79-0), that issue might not be related to the library itself but my different webpack versions in my node_modules.

I close.
